project_id = "xafzdcrgbcudztfukggt"

[functions.aws-dashboard-data]
verify_jwt = true

[functions.save-aws-credentials]
verify_jwt = true

[functions.manage-security-groups]
verify_jwt = true

[functions.manage-iam-users]
verify_jwt = true

[functions.compliance-remediation]
verify_jwt = true

[functions.manage-ec2-instances]
verify_jwt = true

[functions.manage-rds-instances]
verify_jwt = true

[functions.manage-vpcs]
verify_jwt = true

[functions.manage-alert-rules]
verify_jwt = true

[functions.send-ses-email]
verify_jwt = true

[functions.send-alert-notification]
verify_jwt = true