// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xafzdcrgbcudztfukggt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZnpkY3JnYmN1ZHp0ZnVrZ2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODc3MDEsImV4cCI6MjA3Mzc2MzcwMX0.CV6rX9IIwXA2zbfd2ewMRBnn0QGSy8PnoT7rQNaadww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});